### PR TITLE
Display multiple posters

### PR DESCRIPTION
**Pull request by mainlyetcetera**
This pull request:
displays multiple posters to the saved posters view, but styling is still incorrect

### CODE REVIEW

**Comment by mainlyetcetera** [comment]
Right now we are able to display multiple posters in the saved posters view. They are using incorrect styling and do not display cleanly.

**Comment by mainlyetcetera** [comment]
Add proper rendering to displaySavedPosters function!

**Review by pJanks — APPROVED** [review]
I think the code looks great there is some DRYing up that can be done on lines 203 - 206. Other than that I think your underlying issues may lie within the CSS itself as opposed to the JS you have changed. You're already getting the data you want you just need to manipulate the way it is displayed on the DOM in my opinion. There is nothing breaking on my end, though, just some jarring styles to take into consideration as refactors.

**Review by Codeherder19 — APPROVED** [review]
Everything looks good and we have full functionality for Iterations 0 through 3. We will make one more pass to see what we can refactor and to make sure there are no unused variables, query selectors, or event listeners/handlers.

**Pull request merged**
